# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

$:.push File.expand_path("../lib", __FILE__)
require "version"

Gem::Specification.new do |s|
  s.name = "stereosupersonic-userstamp"
  s.version = Ddb::Userstamp::VERSION

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Deimel"]
  s.email = "michael@deimel.de"
  s.extra_rdoc_files = [
    "LICENSE"
  ]
  s.files = [
    "CHANGELOG",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "Rakefile",
    "Readme.rdoc",
    "lib/migration_helper.rb",
    "lib/stampable.rb",
    "lib/stamper.rb",
    "lib/userstamp.rb",
    "stereosupersonic-userstamp.gemspec",
    "rdoc/classes/Ddb/Controller.html",
    "rdoc/classes/Ddb/Controller/Userstamp/InstanceMethods.html",
    "rdoc/classes/Ddb/Userstamp/MigrationHelper.html",
    "rdoc/classes/Ddb/Userstamp/MigrationHelper/InstanceMethods.html",
    "rdoc/classes/Ddb/Userstamp/Stampable.html",
    "rdoc/classes/Ddb/Userstamp/Stampable/ClassMethods.html",
    "rdoc/classes/Ddb/Userstamp/Stamper.html",
    "rdoc/classes/Ddb/Userstamp/Stamper/ClassMethods.html",
    "rdoc/classes/Ddb/Userstamp/Stamper/InstanceMethods.html",
    "rdoc/created.rid",
    "rdoc/files/CHANGELOG.html",
    "rdoc/files/LICENSE.html",
    "rdoc/files/lib/migration_helper_rb.html",
    "rdoc/files/lib/stampable_rb.html",
    "rdoc/files/lib/stamper_rb.html",
    "rdoc/files/lib/userstamp_rb.html",
    "rdoc/fr_class_index.html",
    "rdoc/fr_file_index.html",
    "rdoc/fr_method_index.html",
    "rdoc/index.html",
    "rdoc/rdoc-style.css",
    "test/compatibility_stamping_test.rb",
    "test/controllers/posts_controller.rb",
    "test/controllers/users_controller.rb",
    "test/controllers/userstamp_controller.rb",
    "test/models/comment.rb",
    "test/models/person.rb",
    "test/models/post.rb",
    "test/models/user.rb",
    "test/schema.rb",
    "test/stamping_test.rb",
    "test/userstamp_controller_test.rb"
  ]
  s.homepage = "https://github.com/stereosupersonic/userstamp"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "This Rails plugin extends ActiveRecord::Base to add automatic updating of created_by and updated_by attributes of your models in much the same way that the ActiveRecord::Timestamp module updates created_(at/on) and updated_(at/on) attributes."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

